[[CUDA]]
arch = "aarch64"
git-tree-sha1 = "c1e69e55f7cc766ed5bee76b7c23c20779010446"
libc = "glibc"
os = "linux"

    [[CUDA.download]]
    sha256 = "0393154c75184cd23f3bcd64f3b10f6ff0c35dcd013d6464b289c7bdfffe9972"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.6.0+0/CUDA.v11.6.0.aarch64-linux-gnu.tar.gz"
[[CUDA]]
arch = "powerpc64le"
git-tree-sha1 = "0a2242cc4a9a9cb4e582f6e37f982d1676f203bd"
libc = "glibc"
os = "linux"

    [[CUDA.download]]
    sha256 = "e6878fbd65ede17869c72f98e9c2e89821a1515bd01e61ab76559cfb4e2550af"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.6.0+0/CUDA.v11.6.0.powerpc64le-linux-gnu.tar.gz"
[[CUDA]]
arch = "x86_64"
git-tree-sha1 = "c976d311f71f9f1b1396f84c616de3abe4dcff8a"
libc = "glibc"
os = "linux"

    [[CUDA.download]]
    sha256 = "5ea30350398ca3699578d9910a77e8622af21fed2343c57601ee4ae64f767a40"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.6.0+0/CUDA.v11.6.0.x86_64-linux-gnu.tar.gz"
[[CUDA]]
arch = "x86_64"
git-tree-sha1 = "d1e8e1cbbdbce32c6c334fd66c701a9cbab9c104"
os = "windows"

    [[CUDA.download]]
    sha256 = "23baa25d0a8eadf6ed3fc8aa23795413694ef23558472795bf69b1142b31fd36"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.6.0+0/CUDA.v11.6.0.x86_64-w64-mingw32.tar.gz"
