[[CUDA]]
arch = "aarch64"
git-tree-sha1 = "0f957f6cd616787beda32b6131fd7b88beeb2d0d"
libc = "glibc"
os = "linux"

    [[CUDA.download]]
    sha256 = "6817148b1b8735cb5becc8d9ff5d9306958a85fdd11c444edb9d2412ec7992fc"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.7.1+0/CUDA.v11.7.1.aarch64-linux-gnu.tar.gz"
[[CUDA]]
arch = "powerpc64le"
git-tree-sha1 = "76b74f28fbf2d80aeb63f2c586defa40b5eb5652"
libc = "glibc"
os = "linux"

    [[CUDA.download]]
    sha256 = "892c6eaa1092fdf875dadaaf0dc2ac5a982a21d1358111d9f5020efabb5e5011"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.7.1+0/CUDA.v11.7.1.powerpc64le-linux-gnu.tar.gz"
[[CUDA]]
arch = "x86_64"
git-tree-sha1 = "95e7af32678bd4eaacb036d5f23e4f47e4f68429"
libc = "glibc"
os = "linux"

    [[CUDA.download]]
    sha256 = "29d7bf3ff10eeb7188badf081dcbff5cf7e161741acb0257d0d919907ea9fd25"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.7.1+0/CUDA.v11.7.1.x86_64-linux-gnu.tar.gz"
[[CUDA]]
arch = "x86_64"
git-tree-sha1 = "5244783cdea83b2f4a1929b5def9cf7295ad85e8"
os = "windows"

    [[CUDA.download]]
    sha256 = "bba397b8df2e925557481342b37ee757ca80b2bc6344229d95fd4851ac4edffd"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.7.1+0/CUDA.v11.7.1.x86_64-w64-mingw32.tar.gz"
