[[CUDA]]
arch = "aarch64"
git-tree-sha1 = "8b207e362024abc8007de6b3fe8e336af9869280"
libc = "glibc"
os = "linux"

    [[CUDA.download]]
    sha256 = "553382d13804290675ccd5dda4b98c0ef80978394a3526bde60793c36db46353"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.4.0+0/CUDA.v11.4.0.aarch64-linux-gnu.tar.gz"
[[CUDA]]
arch = "powerpc64le"
git-tree-sha1 = "2068f47091b9a7a16bcb5f06ef8dd311ddf2864f"
libc = "glibc"
os = "linux"

    [[CUDA.download]]
    sha256 = "edc839234252235501847ce63f936542d5e70ca72a045ecd20e88e2016a5782d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.4.0+0/CUDA.v11.4.0.powerpc64le-linux-gnu.tar.gz"
[[CUDA]]
arch = "x86_64"
git-tree-sha1 = "a97e3f13b77cbfdbedd9935c7c9311ebc5eed9bb"
libc = "glibc"
os = "linux"

    [[CUDA.download]]
    sha256 = "d8c73b284e2a69e23e53abe4c550efdceb735388bb25d12fd8facd528d892fd6"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.4.0+0/CUDA.v11.4.0.x86_64-linux-gnu.tar.gz"
[[CUDA]]
arch = "x86_64"
git-tree-sha1 = "90484fce64a2e78c41a8723ef521ec417c0a8f1b"
os = "windows"

    [[CUDA.download]]
    sha256 = "7c0a565ab1f40d630d2de7f4ca94341105695bc97133daf0d54dfd78ba840048"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.4.0+0/CUDA.v11.4.0.x86_64-w64-mingw32.tar.gz"
