[[CUDA]]
arch = "x86_64"
git-tree-sha1 = "f33c3a9317b43ec83abaf5bb401af9bbd42a4803"
libc = "glibc"
os = "linux"

    [[CUDA.download]]
    sha256 = "2d1b0c6e00fd37452cee329bab0765e6fd436a3d0a868fdac2abaa58b2e30a91"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.2.89+1/CUDA.v10.2.89.x86_64-linux-gnu.tar.gz"
[[CUDA]]
arch = "x86_64"
git-tree-sha1 = "7d170cd68590442ec4dbf5a21cda63230664fd51"
os = "windows"

    [[CUDA.download]]
    sha256 = "fd291ad9844fec9486dd4637ea4ab2d942aa4fde13c4e4252e2d726ef3d78d5b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.2.89+1/CUDA.v10.2.89.x86_64-w64-mingw32.tar.gz"
