[[CUDA]]
arch = "aarch64"
git-tree-sha1 = "72bc96813eadede52634bc4977ea5e9da73c51ba"
libc = "glibc"
os = "linux"

    [[CUDA.download]]
    sha256 = "ceb2f8c19930321599c17dcd002b3a03cc2889861d4e7bbb85e94f11bdbf74dd"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.4.4+0/CUDA.v11.4.4.aarch64-linux-gnu.tar.gz"
[[CUDA]]
arch = "powerpc64le"
git-tree-sha1 = "d10124ce5f2c270a2e061d5b41a9c2590bf221c1"
libc = "glibc"
os = "linux"

    [[CUDA.download]]
    sha256 = "66d84dd0f44f409b6c96f48e23a70a02f1831a48e57f7e574d8912d5ce02edb2"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.4.4+0/CUDA.v11.4.4.powerpc64le-linux-gnu.tar.gz"
[[CUDA]]
arch = "x86_64"
git-tree-sha1 = "710ac291467590e0567804b0f0e77638f22b9189"
libc = "glibc"
os = "linux"

    [[CUDA.download]]
    sha256 = "b6f74e7182a774a909b3542854ea53d41e41c1da066a672f1772bde8419261ba"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.4.4+0/CUDA.v11.4.4.x86_64-linux-gnu.tar.gz"
[[CUDA]]
arch = "x86_64"
git-tree-sha1 = "08c6d9708ccf6a1b3cde68faca79828bf5c095cf"
os = "windows"

    [[CUDA.download]]
    sha256 = "c73fca65757c7e1bb8dc9ef22bd1b8f81da1b323b33bf46dd38ea5f58c87fd77"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.4.4+0/CUDA.v11.4.4.x86_64-w64-mingw32.tar.gz"
