[[CUDA]]
arch = "aarch64"
git-tree-sha1 = "c10fc05b1f7f23224377a5520ce381a5cd209a70"
libc = "glibc"
os = "linux"

    [[CUDA.download]]
    sha256 = "9314efe2af6ee52bed2f712ca89be9f3ab6935f5ffad4fd5d5558cac7d957152"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.4.1+0/CUDA.v11.4.1.aarch64-linux-gnu.tar.gz"
[[CUDA]]
arch = "powerpc64le"
git-tree-sha1 = "998ccd7b123ab7cab84a5ef0be5ab74f6d546df4"
libc = "glibc"
os = "linux"

    [[CUDA.download]]
    sha256 = "10c36e463661d9fd203693f1953a1ed65628277c2cf5a81c226ca1a0ff0e5e94"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.4.1+0/CUDA.v11.4.1.powerpc64le-linux-gnu.tar.gz"
[[CUDA]]
arch = "x86_64"
git-tree-sha1 = "b9850068a41d7f48958dcef98d18c9e5614f8062"
libc = "glibc"
os = "linux"

    [[CUDA.download]]
    sha256 = "9b5b81c6c09343f78d3d66555718b6aae9fb8afc837f5e245f27ba9e9cca917c"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.4.1+0/CUDA.v11.4.1.x86_64-linux-gnu.tar.gz"
[[CUDA]]
arch = "x86_64"
git-tree-sha1 = "a1a928604cd2cba424407d6f7650d44a07ba9bf4"
os = "windows"

    [[CUDA.download]]
    sha256 = "1d8928945771b46978008aead08c678463dcaee043182f8175b35f88322be097"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.4.1+0/CUDA.v11.4.1.x86_64-w64-mingw32.tar.gz"
