[[CUDA]]
arch = "powerpc64le"
git-tree-sha1 = "c6ea42b751ea49a0db0b619cf14beb5b63f5ca76"
libc = "glibc"
os = "linux"

    [[CUDA.download]]
    sha256 = "e09f0435b629920777317c2cfe323101bea83028f5dee4fcdc0c67a9a681000f"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.3.1+0/CUDA.v11.3.1.powerpc64le-linux-gnu.tar.gz"
[[CUDA]]
arch = "x86_64"
git-tree-sha1 = "8a3d496042e9fa5d3302e54d24766fdd5f97fbc3"
libc = "glibc"
os = "linux"

    [[CUDA.download]]
    sha256 = "b28ddb34d6368c36aeaa5a81310640ce2f471fbe1959028ab989caf861c76f91"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.3.1+0/CUDA.v11.3.1.x86_64-linux-gnu.tar.gz"
[[CUDA]]
arch = "x86_64"
git-tree-sha1 = "624a58c7b0f3dd3237bef008931b26c2a631a181"
os = "windows"

    [[CUDA.download]]
    sha256 = "601f65cbea6239741431b00d7703f7ddaade011e76cfa9f6fc0e4678a9c1abf0"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.3.1+0/CUDA.v11.3.1.x86_64-w64-mingw32.tar.gz"
