[[CUDA]]
arch = "powerpc64le"
git-tree-sha1 = "6e53efb776f68465afade713092fa8eb27431173"
libc = "glibc"
os = "linux"

    [[CUDA.download]]
    sha256 = "f3571fc1d4fd2497dafd2258b1fa27b8ac94a4adc25b7cde5fa689ffbd484809"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.1.0+1/CUDA.v11.1.0.powerpc64le-linux-gnu.tar.gz"
[[CUDA]]
arch = "x86_64"
git-tree-sha1 = "23ec8861ac0539b1549ce37ba12a88182c28adb4"
libc = "glibc"
os = "linux"

    [[CUDA.download]]
    sha256 = "0363d6b3277ab9cec365902d8ba6b3fb33ccc8b5050fa78f6ab8d57f3aede539"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.1.0+1/CUDA.v11.1.0.x86_64-linux-gnu.tar.gz"
[[CUDA]]
arch = "x86_64"
git-tree-sha1 = "75593c2ea86a066db0435c3e73dd82cbed892e6f"
os = "windows"

    [[CUDA.download]]
    sha256 = "84d45a14538db03f9e9db7debadfb02394f0fa4964c1fb888cec0f33606305c2"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.1.0+1/CUDA.v11.1.0.x86_64-w64-mingw32.tar.gz"
