# Autogenerated wrapper script for CUDA_jll for x86_64-apple-darwin
export libcublas, libcudadevrt, libcudart, libcufft, libcufftw, libcupti, libcurand, libcusolver, libcusparse, libdevice, libnppc, libnppial, libnppicc, libnppicom, libnppidei, libnppif, libnppig, libnppim, libnppist, libnppisu, libnppitc, libnpps, libnvblas, libnvgraph, libnvtoolsext, libnvvm, nvdisasm

JLLWrappers.@generate_wrapper_header("CUDA")
JLLWrappers.@declare_library_product(libcublas, "@rpath/libcublas.9.2.dylib")
JLLWrappers.@declare_file_product(libcudadevrt)
JLLWrappers.@declare_library_product(libcudart, "@rpath/libcudart.9.2.dylib")
JLLWrappers.@declare_library_product(libcufft, "@rpath/libcufft.9.2.dylib")
JLLWrappers.@declare_library_product(libcufftw, "@rpath/libcufftw.9.2.dylib")
JLLWrappers.@declare_library_product(libcupti, "@rpath/libcupti.9.2.dylib")
JLLWrappers.@declare_library_product(libcurand, "@rpath/libcurand.9.2.dylib")
JLLWrappers.@declare_library_product(libcusolver, "@rpath/libcusolver.9.2.dylib")
JLLWrappers.@declare_library_product(libcusparse, "@rpath/libcusparse.9.2.dylib")
JLLWrappers.@declare_file_product(libdevice)
JLLWrappers.@declare_library_product(libnppc, "@rpath/libnppc.9.2.dylib")
JLLWrappers.@declare_library_product(libnppial, "@rpath/libnppial.9.2.dylib")
JLLWrappers.@declare_library_product(libnppicc, "@rpath/libnppicc.9.2.dylib")
JLLWrappers.@declare_library_product(libnppicom, "@rpath/libnppicom.9.2.dylib")
JLLWrappers.@declare_library_product(libnppidei, "@rpath/libnppidei.9.2.dylib")
JLLWrappers.@declare_library_product(libnppif, "@rpath/libnppif.9.2.dylib")
JLLWrappers.@declare_library_product(libnppig, "@rpath/libnppig.9.2.dylib")
JLLWrappers.@declare_library_product(libnppim, "@rpath/libnppim.9.2.dylib")
JLLWrappers.@declare_library_product(libnppist, "@rpath/libnppist.9.2.dylib")
JLLWrappers.@declare_library_product(libnppisu, "@rpath/libnppisu.9.2.dylib")
JLLWrappers.@declare_library_product(libnppitc, "@rpath/libnppitc.9.2.dylib")
JLLWrappers.@declare_library_product(libnpps, "@rpath/libnpps.9.2.dylib")
JLLWrappers.@declare_library_product(libnvblas, "@rpath/libnvblas.9.2.dylib")
JLLWrappers.@declare_library_product(libnvgraph, "@rpath/libnvgraph.9.2.dylib")
JLLWrappers.@declare_library_product(libnvtoolsext, "@rpath/libnvToolsExt.1.dylib")
JLLWrappers.@declare_library_product(libnvvm, "@rpath/libnvvm.3.2.0.dylib")
JLLWrappers.@declare_executable_product(nvdisasm)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcublas,
        "lib/libcublas.9.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libcudadevrt,
        "lib/libcudadevrt.a",
    )

    JLLWrappers.@init_library_product(
        libcudart,
        "lib/libcudart.9.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcufft,
        "lib/libcufft.9.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcufftw,
        "lib/libcufftw.9.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcupti,
        "lib/libcupti.9.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcurand,
        "lib/libcurand.9.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcusolver,
        "lib/libcusolver.9.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcusparse,
        "lib/libcusparse.9.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libdevice,
        "share/libdevice/libdevice.10.bc",
    )

    JLLWrappers.@init_library_product(
        libnppc,
        "lib/libnppc.9.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnppial,
        "lib/libnppial.9.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnppicc,
        "lib/libnppicc.9.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnppicom,
        "lib/libnppicom.9.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnppidei,
        "lib/libnppidei.9.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnppif,
        "lib/libnppif.9.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnppig,
        "lib/libnppig.9.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnppim,
        "lib/libnppim.9.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnppist,
        "lib/libnppist.9.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnppisu,
        "lib/libnppisu.9.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnppitc,
        "lib/libnppitc.9.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnpps,
        "lib/libnpps.9.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnvblas,
        "lib/libnvblas.9.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnvgraph,
        "lib/libnvgraph.9.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnvtoolsext,
        "lib/libnvToolsExt.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnvvm,
        "lib/libnvvm.3.2.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        nvdisasm,
        "bin/nvdisasm",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
